/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Path_parametric_MPC_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[12] = {10, 1, 0, 8, 2, 3, 4, 5, 6, 7, 8, 9};

/* Path_parametric_MPC_expl_vde_adj:(i0[8],i1[8],i2[2],i3[])->(o0[10x1,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 8, w3);
  /* #4: {@4, @5, @6, @7, @8, @9, @10, @11} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  w10 = w3[6];
  w11 = w3[7];
  /* #5: @12 = (@2*@5) */
  w12  = (w2*w5);
  /* #6: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #7: @14 = (@13*@4) */
  w14  = (w13*w4);
  /* #8: @12 = (@12-@14) */
  w12 -= w14;
  /* #9: @1 = (@1*@12) */
  w1 *= w12;
  /* #10: @12 = sin(@0) */
  w12 = sin( w0 );
  /* #11: @14 = (@13*@5) */
  w14  = (w13*w5);
  /* #12: @15 = (@2*@4) */
  w15  = (w2*w4);
  /* #13: @14 = (@14+@15) */
  w14 += w15;
  /* #14: @12 = (@12*@14) */
  w12 *= w14;
  /* #15: @1 = (@1-@12) */
  w1 -= w12;
  /* #16: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #17: @1 = 0.1 */
  w1 = 1.0000000000000001e-01;
  /* #18: @12 = (@1<=@2) */
  w12  = (w1<=w2);
  /* #19: @14 = 0.029 */
  w14 = 2.9000000000000001e-02;
  /* #20: @15 = input[0][5] */
  w15 = arg[0] ? arg[0][5] : 0;
  /* #21: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #22: @16 = (@16+@13) */
  w16 += w13;
  /* #23: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #24: @1 = fmax(@2,@1) */
  w1  = casadi_fmax(w2,w1);
  /* #25: @18 = sq(@1) */
  w18 = casadi_sq( w1 );
  /* #26: @17 = (@17+@18) */
  w17 += w18;
  /* #27: @18 = (@16/@17) */
  w18  = (w16/w17);
  /* #28: @19 = 2.579 */
  w19 = 2.5790000000000002e+00;
  /* #29: @20 = 1.2 */
  w20 = 1.2000000000000000e+00;
  /* #30: @21 = input[0][6] */
  w21 = arg[0] ? arg[0][6] : 0;
  /* #31: @16 = atan2(@16,@1) */
  w16  = atan2(w16,w1);
  /* #32: @16 = (@21-@16) */
  w16  = (w21-w16);
  /* #33: @16 = (@19*@16) */
  w16  = (w19*w16);
  /* #34: @22 = atan(@16) */
  w22 = atan( w16 );
  /* #35: @22 = (@20*@22) */
  w22  = (w20*w22);
  /* #36: @23 = cos(@22) */
  w23 = cos( w22 );
  /* #37: @24 = 0.192 */
  w24 = 1.9200000000000000e-01;
  /* #38: @25 = 0.029 */
  w25 = 2.9000000000000001e-02;
  /* #39: @26 = cos(@21) */
  w26 = cos( w21 );
  /* #40: @27 = 35971.2 */
  w27 = 3.5971223021582729e+04;
  /* #41: @27 = (@27*@9) */
  w27 *= w9;
  /* #42: @9 = (@26*@27) */
  w9  = (w26*w27);
  /* #43: @9 = (@25*@9) */
  w9  = (w25*w9);
  /* #44: @28 = 24.3902 */
  w28 = 2.4390243902439025e+01;
  /* #45: @28 = (@28*@8) */
  w28 *= w8;
  /* #46: @26 = (@26*@28) */
  w26 *= w28;
  /* #47: @9 = (@9+@26) */
  w9 += w26;
  /* #48: @26 = sin(@21) */
  w26 = sin( w21 );
  /* #49: @29 = 24.3902 */
  w29 = 2.4390243902439025e+01;
  /* #50: @29 = (@29*@7) */
  w29 *= w7;
  /* #51: @26 = (@26*@29) */
  w26 *= w29;
  /* #52: @9 = (@9-@26) */
  w9 -= w26;
  /* #53: @9 = (@24*@9) */
  w9  = (w24*w9);
  /* #54: @23 = (@23*@9) */
  w23 *= w9;
  /* #55: @20 = (@20*@23) */
  w20 *= w23;
  /* #56: @23 = 1 */
  w23 = 1.;
  /* #57: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #58: @23 = (@23+@16) */
  w23 += w16;
  /* #59: @20 = (@20/@23) */
  w20 /= w23;
  /* #60: @19 = (@19*@20) */
  w19 *= w20;
  /* #61: @18 = (@18*@19) */
  w18 *= w19;
  /* #62: @20 = 0.033 */
  w20 = 3.3000000000000002e-02;
  /* #63: @23 = (@20*@15) */
  w23  = (w20*w15);
  /* #64: @23 = (@23-@13) */
  w23 -= w13;
  /* #65: @16 = sq(@23) */
  w16 = casadi_sq( w23 );
  /* #66: @9 = sq(@1) */
  w9 = casadi_sq( w1 );
  /* #67: @16 = (@16+@9) */
  w16 += w9;
  /* #68: @9 = (@23/@16) */
  w9  = (w23/w16);
  /* #69: @26 = 3.3852 */
  w26 = 3.3852000000000002e+00;
  /* #70: @30 = 1.2691 */
  w30 = 1.2690999999999999e+00;
  /* #71: @23 = atan2(@23,@1) */
  w23  = atan2(w23,w1);
  /* #72: @23 = (@26*@23) */
  w23  = (w26*w23);
  /* #73: @31 = atan(@23) */
  w31 = atan( w23 );
  /* #74: @31 = (@30*@31) */
  w31  = (w30*w31);
  /* #75: @31 = cos(@31) */
  w31 = cos( w31 );
  /* #76: @32 = 0.1737 */
  w32 = 1.7369999999999999e-01;
  /* #77: @33 = 0.033 */
  w33 = 3.3000000000000002e-02;
  /* #78: @33 = (@33*@27) */
  w33 *= w27;
  /* #79: @33 = (@28-@33) */
  w33  = (w28-w33);
  /* #80: @32 = (@32*@33) */
  w32 *= w33;
  /* #81: @31 = (@31*@32) */
  w31 *= w32;
  /* #82: @30 = (@30*@31) */
  w30 *= w31;
  /* #83: @31 = 1 */
  w31 = 1.;
  /* #84: @23 = sq(@23) */
  w23 = casadi_sq( w23 );
  /* #85: @31 = (@31+@23) */
  w31 += w23;
  /* #86: @30 = (@30/@31) */
  w30 /= w31;
  /* #87: @26 = (@26*@30) */
  w26 *= w30;
  /* #88: @9 = (@9*@26) */
  w9 *= w26;
  /* #89: @18 = (@18-@9) */
  w18 -= w9;
  /* #90: @12 = (@12*@18) */
  w12 *= w18;
  /* #91: @18 = (@15*@8) */
  w18  = (w15*w8);
  /* #92: @12 = (@12-@18) */
  w12 -= w18;
  /* #93: @18 = (2.*@2) */
  w18 = (2.* w2 );
  /* #94: @9 = 0.00035 */
  w9 = 3.5000000000000000e-04;
  /* #95: @30 = sign(@2) */
  w30 = casadi_sign( w2 );
  /* #96: @30 = (@30*@29) */
  w30 *= w29;
  /* #97: @9 = (@9*@30) */
  w9 *= w30;
  /* #98: @18 = (@18*@9) */
  w18 *= w9;
  /* #99: @12 = (@12-@18) */
  w12 -= w18;
  /* #100: @18 = 5 */
  w18 = 5.;
  /* #101: @9 = 1 */
  w9 = 1.;
  /* #102: @30 = (@18*@2) */
  w30  = (w18*w2);
  /* #103: @30 = tanh(@30) */
  w30 = tanh( w30 );
  /* #104: @30 = sq(@30) */
  w30 = casadi_sq( w30 );
  /* #105: @9 = (@9-@30) */
  w9 -= w30;
  /* #106: @30 = 0.0518 */
  w30 = 5.1799999999999999e-02;
  /* #107: @30 = (@30*@29) */
  w30 *= w29;
  /* #108: @9 = (@9*@30) */
  w9 *= w30;
  /* #109: @18 = (@18*@9) */
  w18 *= w9;
  /* #110: @12 = (@12-@18) */
  w12 -= w18;
  /* #111: @18 = sign(@2) */
  w18 = casadi_sign( w2 );
  /* #112: @9 = 0.0545 */
  w9 = 5.4500000000000000e-02;
  /* #113: @30 = input[0][7] */
  w30 = arg[0] ? arg[0][7] : 0;
  /* #114: @30 = (@30*@29) */
  w30 *= w29;
  /* #115: @30 = (@9*@30) */
  w30  = (w9*w30);
  /* #116: @18 = (@18*@30) */
  w18 *= w30;
  /* #117: @12 = (@12-@18) */
  w12 -= w18;
  /* #118: @18 = sin(@0) */
  w18 = sin( w0 );
  /* #119: @30 = (@18*@5) */
  w30  = (w18*w5);
  /* #120: @12 = (@12+@30) */
  w12 += w30;
  /* #121: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #122: @30 = (@0*@4) */
  w30  = (w0*w4);
  /* #123: @12 = (@12+@30) */
  w12 += w30;
  /* #124: output[0][1] = @12 */
  if (res[0]) res[0][1] = w12;
  /* #125: @15 = (@15*@7) */
  w15 *= w7;
  /* #126: @16 = (@1/@16) */
  w16  = (w1/w16);
  /* #127: @16 = (@16*@26) */
  w16 *= w26;
  /* #128: @15 = (@15-@16) */
  w15 -= w16;
  /* #129: @1 = (@1/@17) */
  w1 /= w17;
  /* #130: @1 = (@1*@19) */
  w1 *= w19;
  /* #131: @15 = (@15-@1) */
  w15 -= w1;
  /* #132: @0 = (@0*@5) */
  w0 *= w5;
  /* #133: @15 = (@15+@0) */
  w15 += w0;
  /* #134: @18 = (@18*@4) */
  w18 *= w4;
  /* #135: @15 = (@15-@18) */
  w15 -= w18;
  /* #136: output[0][2] = @15 */
  if (res[0]) res[0][2] = w15;
  /* #137: @20 = (@20*@16) */
  w20 *= w16;
  /* #138: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #139: @20 = (@20-@8) */
  w20 -= w8;
  /* #140: @13 = (@13*@7) */
  w13 *= w7;
  /* #141: @20 = (@20+@13) */
  w20 += w13;
  /* #142: @14 = (@14*@1) */
  w14 *= w1;
  /* #143: @20 = (@20-@14) */
  w20 -= w14;
  /* #144: @20 = (@20+@6) */
  w20 += w6;
  /* #145: output[0][3] = @20 */
  if (res[0]) res[0][3] = w20;
  /* #146: @20 = cos(@21) */
  w20 = cos( w21 );
  /* #147: @22 = sin(@22) */
  w22 = sin( w22 );
  /* #148: @24 = (@24*@22) */
  w24 *= w22;
  /* #149: @22 = (@24*@29) */
  w22  = (w24*w29);
  /* #150: @20 = (@20*@22) */
  w20 *= w22;
  /* #151: @20 = (-@20) */
  w20 = (- w20 );
  /* #152: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #153: @25 = (@25*@24) */
  w25 *= w24;
  /* #154: @25 = (@25*@27) */
  w25 *= w27;
  /* #155: @24 = (@24*@28) */
  w24 *= w28;
  /* #156: @25 = (@25+@24) */
  w25 += w24;
  /* #157: @21 = (@21*@25) */
  w21 *= w25;
  /* #158: @20 = (@20-@21) */
  w20 -= w21;
  /* #159: @20 = (@20+@19) */
  w20 += w19;
  /* #160: output[0][4] = @20 */
  if (res[0]) res[0][4] = w20;
  /* #161: @20 = 0.287 */
  w20 = 2.8699999999999998e-01;
  /* #162: @2 = fabs(@2) */
  w2 = fabs( w2 );
  /* #163: @9 = (@9*@2) */
  w9 *= w2;
  /* #164: @20 = (@20-@9) */
  w20 -= w9;
  /* #165: @20 = (@20*@29) */
  w20 *= w29;
  /* #166: output[0][5] = @20 */
  if (res[0]) res[0][5] = w20;
  /* #167: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  /* #168: output[0][7] = @11 */
  if (res[0]) res[0][7] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Path_parametric_MPC_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Path_parametric_MPC_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Path_parametric_MPC_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Path_parametric_MPC_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Path_parametric_MPC_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Path_parametric_MPC_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 41;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
